# title: Article Title
# meta: Meta info
# category: Category Info
# tags: Tags info
# cover: Cover Image
# color: Main Color

- path: /_posts/20170106test.md
  title: test1
  meta: test-meta1
  category: swe
  tags: [code, agile]
  cover: http://bulma.io/images/placeholders/1280x960.png
  color: '#606060'
  created: 2017-01-02
- path: /_posts/20170106test.md
  title: test2
  meta: test-meta2
  category: swe
  tags: [code, agile]
  cover: /img/fdsf
  color: '#606060'
  created: 2017-01-02
- path: /_posts/20170106test.md
  title: test4
  meta: test-meta1
  category: swe
  tags: [code, agile]
  cover: http://bulma.io/images/placeholders/1280x960.png
  color: '#606060'
  created: 2017-01-02
- path: /_posts/20170106test.md
  title: test3
  meta: test-meta3
  category: 软件工程
  tags: [code, agile]
  cover: /img/fdsf
  color: '#606060'
  created: 2017-01-02
