# title: Article Title
# meta: Meta info
# category: Category Info
# tags: Tags info
# cover: Cover Image
# color: Main Color

- title: test1
  meta: test-meta1
  category: swe
  tags: [code, agile]
  cover: /img/fdsf
  color: '#606060'
- title: test2
  meta: test-meta2
  category: swe
  tags: [code, agile]
  cover: /img/fdsf
  color: '#606060'
- title: test3
  meta: test-meta3
  category: 软件工程
  tags: [code, agile]
  cover: /img/fdsf
  color: '#606060'
